name: Lint, Type-Check, Test, Build and Publish Package

on:
    pull_request:
        branches: [main]
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Install uv
              uses: astral-sh/setup-uv@v3
              with:
                enable-cache: true
                cache-dependency-glob: uv.lock

            - name: Build Package
              run: uv build --no-sources

            - name: Save Build Artifacts
              uses: actions/upload-artifact@v4
              with:
                name: built-Pydowndoc-package
                path: dist/

    test-publish:
        needs: [build]
        runs-on: ubuntu-latest
        environment: test-publish
        permissions:
            id-token: write

        if: github.ref_type != 'tag'

        steps:
            - uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v3
              with:
                enable-cache: true
                cache-dependency-glob: uv.lock

            - name: Download Build Artifacts
              uses: actions/download-artifact@v4
              with:
                name: built-Pydowndoc-package
                path: dist/

            - name: Publish to Test-PyPI
              run: uv publish --publish-url https://test.pypi.org/legacy/
