name: Upload downdoc Binaries

"on":
    workflow_call: ~
    workflow_dispatch: ~

jobs:
    upload-downdoc-binaries:
        container: ${{fromJSON(matrix.container)}}
        name: Upload ${{matrix.display_os}} ${{matrix.display_architecture}} downdoc binary
        runs-on: ${{matrix.runner}}
        strategy:
            matrix:
                include:
                    - architecture: x86-64
                      container: "{\"image\": \"quay.io/pypa/manylinux_2_34_x86_64\"}"
                      display_architecture: x86_64
                      display_os: Linux
                      downdoc_architecture: x64
                      downdoc_binary_suffix: ""
                      downdoc_os: linux
                      os: linux
                      runner: ubuntu-latest

                    - architecture: x86-64
                      container: "null"
                      display_architecture: x86_64
                      display_os: Windows
                      downdoc_architecture: x64
                      downdoc_binary_suffix: .exe
                      downdoc_os: win
                      os: windows
                      runner: windows-latest

                    - architecture: x86-64
                      container: "null"
                      display_architecture: x86_64
                      display_os: macOS
                      downdoc_architecture: x64
                      downdoc_binary_suffix: ""
                      downdoc_os: macos
                      os: macos
                      runner: macos-13

                    - architecture: arm64
                      container: "{\"image\": \"quay.io/pypa/manylinux_2_34_aarch64\"}"
                      display_architecture: arm64
                      display_os: Linux
                      downdoc_architecture: arm64
                      downdoc_binary_suffix: ""
                      downdoc_os: linux
                      os: linux
                      runner: ubuntu-24.04-arm

        steps:
            - id: checkout-upstream-repository
              uses: actions/checkout@v5
              with:
                ref: v1.0.2-stable
                repository: opendevise/downdoc

            - id: restore-binary-from-cache
              uses: actions/cache@v4
              with:
                key: downdoc-${{matrix.os}}-${{matrix.architecture}}|${{steps.checkout-upstream-repository.outputs.ref}}
                path: Pydowndoc-bin/downloads/downdoc-${{matrix.os}}-${{matrix.architecture}}${{matrix.downdoc_binary_suffix}}

            - if: steps.restore-binary-from-cache.outputs.cache-hit != 'true'
              uses: actions/setup-node@v5
              with:
                node-version: 22

            - if: steps.restore-binary-from-cache.outputs.cache-hit != 'true'
              name: Build downdoc ${{matrix.display_os}} ${{matrix.display_architecture}} binary
              run: npx pkg -t node18-${{matrix.downdoc_os}}-${{matrix.downdoc_architecture}} . --out-path
                Pydowndoc-bin/downloads

            - if: steps.restore-binary-from-cache.outputs.cache-hit != 'true'
              name: Rename built downdoc binary
              run: mv Pydowndoc-bin/downloads/downdoc${{matrix.downdoc_binary_suffix}} Pydowndoc-bin/downloads/downdoc-${{matrix.os}}-${{matrix.architecture}}${{matrix.downdoc_binary_suffix}}

            - uses: actions/upload-artifact@v4
              with:
                if-no-files-found: error
                name: downdoc-${{matrix.os}}-${{matrix.architecture}}-binary
                path: Pydowndoc-bin/downloads/downdoc-${{matrix.os}}-${{matrix.architecture}}${{matrix.downdoc_binary_suffix}}
