name: Upload downdoc Binaries

on:
    workflow_dispatch:
    workflow_call:

jobs:
    upload-linux-x86-64-downdoc-binary:
        runs-on: ubuntu-latest
        container: {image: quay.io/pypa/manylinux_2_34_x86_64}

        steps:
            - uses: actions/checkout@v4
              id: checkout-upstream-repository
              with:
                repository: opendevise/downdoc
                ref: v1.0.2-stable

            - uses: actions/cache@v4
              with:
                path: downloads/downdoc-linux-x64
                key: downdoc-linux-x64|${{steps.checkout-upstream-repository.outputs.ref}}

            - uses: actions/setup-node@v4
              if: steps.cache.outputs.cache-hit != 'true'
              with:
                node-version: 18

            - name: Build downdoc linux-x64 binary
              if: steps.cache.outputs.cache-hit != 'true'
              run: npx pkg -t linux-x64 . --out-path downloads

            - name: Rename built downdoc binary
              if: steps.cache.outputs.cache-hit != 'true'
              run: mv downloads/downdoc downloads/downdoc-linux-x64

            - uses: actions/upload-artifact@v4
              with:
                name: downdoc-linux-x86-64-binary
                path: downloads/downdoc-linux-x64
                if-no-files-found: error
