name: Upload downdoc Binaries

on:
    workflow_dispatch:
    workflow_call:

jobs:
    upload-linux-x86-64-downdoc-binary:
        runs-on: ubuntu-latest
        container: {image: quay.io/pypa/manylinux_2_34_x86_64}

        steps:
            - uses: actions/checkout@v4
              with:
                repository: opendevise/downdoc

            - uses: actions/setup-node@v4
              with:
                node-version: 18

            - run: npx pkg -t linux-x64 . --out-path downloads

            - uses: actions/upload-artifact@v4
              with:
                name: downdoc-linux-x86-64-binary
                path: downloads/downdoc-linux-x86-64
